name: Verify Human Identity

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: 'limitzaja'
        required: true
        default: 'limitzaja'
      agent_description:
        description: 'limitzaja'
        required: true
        default: 'limitzaja AI Agent'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "Agent Name: ${{ github.event.inputs.agent_name }}"
          echo "Agent Description: ${{ github.event.inputs.agent_description }}"
